### ISSUE TITLE
UI Wireframing 

### ISSUE THREAD

**Issue by engramar** [codesydney/jrdev#2]
Hi @rpgarde, As discussed, please try to come up with a very rudimentary design. You can refer to the high-level diagram in our wiki page  https://github.com/codesydney/jrdev/wiki to get a picture of the end-to-end flow. Try to align the screens based on each defined epic.  Thanks.

**Comment by rpgarde** [comment]
Initial wireframe brainstorm here https://docs.google.com/presentation/d/1URAoHkMmKQz-GJv3c3BWpoya7knMxrNzFQ5HlI0LiXU/edit#slide=id.p
